"""Missed letter

Revision ID: 2a7c481fab66
Revises: 437e3b61b14a
Create Date: 2023-07-10 00:26:50.694443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7c481fab66'
down_revision = '437e3b61b14a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.drop_column('contacts', 'fist_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('fist_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('contacts', 'first_name')
    # ### end Alembic commands ###
